# Generated by Django 4.1 on 2023-01-03 11:58

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ExpenseTrack", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=100)),
                ("group_members", jsonfield.fields.JSONField(default={"members": []})),
                ("group_expense", models.CharField(default="0", max_length=100)),
                (
                    "group_transcations",
                    jsonfield.fields.JSONField(default={"transcations": []}),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user_data",
            name="budget",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="user_data",
            name="expense",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="user_data",
            name="transcations",
            field=jsonfield.fields.JSONField(default={"transcations": []}),
        ),
    ]
