# Generated by Django 4.1 on 2023-01-03 11:59

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ExpenseTrack", "0002_group_user_data_budget_user_data_expense_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_data",
            name="friends",
            field=jsonfield.fields.JSONField(default={"friends": []}),
        ),
    ]
