# Generated by Django 4.1 on 2023-01-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ExpenseTrack", "0003_user_data_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_data",
            name="income",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
