# Generated by Django 4.1 on 2023-01-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ExpenseTrack", "0004_user_data_income"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_data", old_name="budget", new_name="savings",
        ),
        migrations.AddField(
            model_name="user_data",
            name="profession",
            field=models.CharField(default="", max_length=100),
        ),
    ]
